python script_1_create_prompts_for_features.py

# run prompt: data_output/prompt_for_features_highlights_of_shops.txt

python script_2_create_prompts_and_python_scripts_for_contents.py

python script_3_create_prompts_for_intro_and_conclusion.py

# run all prompts in contents directory

python script_4_run_all_generate_html_python_script.py

python script_5_create_combined_post_html.py